Repository kubermatic/utils, pull requests merged in 2020-07, with the labels that each got.

#4 Remove validate-prow from .prow.yaml
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#3 Improved NewReconrdingClient API
  pkg/testutil/recording_client.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#5 Add poll-based UpdateObject function
  pkg/testutil/helpers.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#6 Update Owner package to handle single owner override
  pkg/owner/owner.go
  pkg/owner/owner_test.go
  pkg/owner/reconcile.go
  pkg/owner/reconcile_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#9 Add Goreleaser for release
  .goreleaser.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/M

#11 System under test
  .goreleaser.yml
  cmd/sut/main.go
  go.mod
  go.sum
  pkg/ide/intelij.go
  pkg/ide/task.go
  pkg/ide/vscode.go
  pkg/sut/service.go
  pkg/sut/service_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#13 Fix CmdLogMixin
  go.mod
  go.sum
  pkg/util/cmd.go
  pkg/util/cmd_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#14 Use vanity import k8c.io/utils
  cmd/sut/main.go
  go.mod
  pkg/ide/task.go
  pkg/multiowner/multi_owner.go
  pkg/multiowner/multi_owner_test.go
  pkg/owner/reconcile.go
  pkg/owner/reconcile_test.go
  pkg/sut/service.go
  pkg/testutil/helpers.go
  pkg/testutil/recording_client.go
Labels: approved, dco-signoff: yes, lgtm, size/S
